### ISSUE TITLE
Ability to use an existing photo 

### ISSUE THREAD

**Issue by patcon** [jessamynsmith/my-bike-lane-mobile#1]
Snapping a quick picture is often simpler using the native camera app. I took one with that, then found a place to lean my bike and opened up the app to create an issue, and couldn't add it. As I was doing this, the truck drove away :)

**Comment by jessamynsmith** [comment]
Absolutely agree. I started work on this feature, but attachment isn't working correctly yet.

**Comment by jessamynsmith** [comment]
I believe this is working correctly now.
